import React from "react";
import { Activity, AlertTriangle, FileAudio, Mic2 } from "lucide-react";
import { SectionTitle } from "./Layout";

export function TrustPanel(){return <section className="panel"><SectionTitle icon={<Activity size={15}/>} title="Continuous Trust Score" subtitle="Confidence across multiple signals in real-time"/><div className="trust-score">18 <small>/100</small><b>CRITICAL</b></div><div className="mini-line"/><div className="signal-grid">{["Synthetic speech signal","Acoustic anomaly","Behavioural urgency signal","Transaction context","High similarity with synthetic indicators"].map((x,i)=><div key={x}><span>{x}</span><b>−{[23,14,22,19,9][i]}</b></div>)}</div></section>}
export function Timeline(){let arr=["Call connected","Speaker identified","Synthetic speech indicators detected","Authority claim detected","Urgency detected","Financial request detected","Name beneficiary detected","High-value request confirmed","Sensitive action paused"];return <section className="panel"><SectionTitle icon={<Activity size={15}/>} title="Attack Timeline" subtitle="Signals, risk changes and audit trail over the call"/><div className="timeline">{arr.map((x,i)=><div key={x}><time>00:{String(i+3).padStart(2,"0")}</time><span>{x}</span><b>{i<2?15:18+i*7}</b></div>)}</div></section>}
export function WhyFlagged(){return <section className="panel"><SectionTitle icon={<AlertTriangle size={15}/>} title="Why Flagged"/><div className="flag-grid">{["VOICE","IDENTITY","BEHAVIOUR","TRANSACTION"].map((x,i)=><div key={x}><b>{x}</b><span>{["High synthetic speech indicators","High similarity to registered speaker","Urgency and authority signals detected","High-value transaction context"][i]}</span></div>)}</div></section>}
export function TransactionContext(){return <section className="panel"><SectionTitle icon={<Activity size={15}/>} title="Transaction Context"/><div className="tx-grid"><div><small>AMOUNT</small><b>₹25,00,000</b></div><div><small>BENEFICIARY</small><b className="red-text">NEW</b></div><div><small>CALLER ROLE</small><b>CFO</b></div><div><small>TRANSACTION RISK</small><b className="red-text">91 / HIGH</b></div></div></section>}
export function VoiceChallenge(){return <section className="panel"><SectionTitle icon={<Mic2 size={15}/>} title="Active Voice Challenge"/><button className="primary-btn">Start voice challenge</button><p className="muted">Ask a challenge phrase and compare live voice against the registered profile.</p></section>}
export function AuditTrail(){return <section className="panel"><SectionTitle icon={<FileAudio size={15}/>} title="Audit Trail"/><p className="muted">No analyst actions recorded yet in this session.</p></section>}
